<?php 
	$improvedcrops = $this->improvedcrops;
?>
<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Improved Crops</h2>
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li class="active"><a href="">Improved Crops</a></li>
        </ol>
      </div> <!-- /.content-header -->
	
      	
      
      <div class="row">

        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-table"></i>
                Improved Crop Technologies
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true">
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Crop</th>
                      <th data-filterable="true" data-sortable="true">Variety</th>
                      <th data-filterable="true" class="-xs -sm">Location</th>
                      <th data-filterable="true" class="-xs hdden-sm">Food Value</th>
                      <th data-filterable="true" class="hidden-xs hidden-sm">Date</th>
                      <th data-filterable="false" class="text-center hidden-xs hidden-sm">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php 
                    	foreach ($improvedcrops as $improvedcrop) {
							
                    ?>
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td>
                      	<a href="/improved-crops/view/id/<?php if($improvedcrop->id){ echo $improvedcrop->id; } ?> ">
                      	<?php 
                      		if($improvedcrop->crop){ echo $improvedcrop->crop; }
                      	?> 
                      	</a>
                      	</td>
                      
                      <td>
                      	<?php 
                      		if($improvedcrop->variety){ echo $improvedcrop->variety; }
                      	?> 
                      </td>
                      <td>
                      	<?php 
                      		if($improvedcrop->location){ echo $improvedcrop->location; }
                      	?> 
                      </td>
                      <td>
                      	<?php 
                      		if($improvedcrop->foodvalue){ echo $improvedcrop->foodvalue; }
                      	?> 
                      </td>
                      <td class="hidden-xs hidden-sm">
                      	<?php 
                      		if($improvedcrop->daterecorded){ echo $improvedcrop->daterecorded; }
                      	?> 
                      </td>
                      <td class="text-center">
                      &nbsp;
                      <a href="/improved-crops/view/id/<?php if($improvedcrop->id){ echo $improvedcrop->id; } ?> " class="btn btn-xs btn-success"><i class="fa fa-eye"></i> view</a>
                      </td>
                    </tr>
                    
                    <?php } ?>
                    
                  </tbody>
                </table>
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        

        </div> <!-- /.col -->

      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->