<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Compose Survey</h2>
        <ol class="breadcrumb">
          <li><a href="/hub">Dashboard</a></li>
          <li><a href="/Surveyweb">Survey</a></li>
          <li class="active">Compose Survey</li>
        </ol>
      </div> <!-- /.content-header -->

      

      <div class="row">

        <div class="col-md-6 col-sm-9">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-hand-o-up"></i>
               Compose Survey
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">

              <form role="form" method="POST" action="/surveyweb/compose">
                  <div class="form-group">
                    <label for="exampleInputEmail1">Survey Title</label>
                    <textarea class="form-control" name="shortname" placeholder="Type survey title" rows="1"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Survey code</label>
                    <textarea class="form-control" name="code" placeholder="survey1" rows="1"></textarea>
                  </div>
                  <div class="form-group">
                    <label for="exampleInputEmail1">Survey Description</label>
                    <textarea class="form-control" name="description" placeholder="Short Description" rows="2"></textarea>
                  </div>
                  <div>                
                  <button type="submit" class="btn btn-success">Submit and add questions</button>
                  <!-- <button type="submit" class="btn btn-default">DRAFT</button> -->
                  </div>
                </form>
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        </div><!-- /.col -->
	
	<div class="col-md-6 col-sm-3">
		<!-- Real estate for the future -->
	</div>


        


      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->