<?php
$categories = $this->categories;
?>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <h1>Browse Courses</h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="/articles">Articles</a></li>
            </ol>
            
        </div>
    </div>
</div> <!-- /container -->
<div class="container">
    <div class="lessons-wrap">
        <div class="class-thumbs-wrap">
            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <div class="coursthumbs">
                        <ul class="nopadding nomargin listnone listing-view">
                         
                        
                             <?php foreach ($categories as $category) { ?>
                            <li class="less-listing course-thumbs cats">
                                <a href=""></a>
                                <div class="bg-arrow">
                                    <div class="row">
                                        <div class="col-xs-5 col-sm-5">
                                            <div class="cat-image">
                                                <a href="/articles/category/<?php echo $category->TE_category_slug ?>"><img src="/images/content/samplecat.jpg" alt="category"/></a>
                                            </div>
                                        </div>
                                        <div class="col-xs-7 col-sm-7">
                                            <div class="less-title">
                                                <a href="/articles/category/<?php echo $category->TE_category_slug ?>"> <?php print_r($category->TE_categories); ?></a>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </li>
                             <?php } ?>
                   
                         
                            
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12">
                    <p class="center nomargin"> <a href="#" class="btn btn-default long-btn"><img class="home-search-icon" src="/images/arrows/more.png" />View by week</a></p>
                </div>


            </div>

        </div>
    </div>
</div>




