-- MySQL Script generated by MySQL Workbench
-- Wed Jul  2 22:03:56 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proussd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proussd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `proussd` ;

-- -----------------------------------------------------
-- Table `proussd`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proussd`.`menu` (
  `id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proussd`.`menu_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proussd`.`menu_item` (
  `id` INT NOT NULL,
  `menu_id` INT NULL,
  `description` VARCHAR(45) NULL,
  `next_menu_id` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  CONSTRAINT `menu_id`
    FOREIGN KEY (`id`)
    REFERENCES `proussd`.`menu` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `next_menu_id`
    FOREIGN KEY (`id`)
    REFERENCES `proussd`.`menu` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proussd`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proussd`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NULL,
  `menu_item_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `menu_item_id`
    FOREIGN KEY (`id`)
    REFERENCES `proussd`.`menu_item` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
