<?php $weekContent = $this->weekContent;
?>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <h1>Week <?php echo $this->week;?></h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="/articles">Articles</a></li>
                <li class="active">Week</li>
            </ol>
        </div>
    </div>
</div> <!-- /container -->
<div class="container">
    <div class="lessons-wrap">
        <div class="class-thumbs-wrap">
            <div class="row">
                <div class="col-xs-12 col-sm-12">
                    <div class="coursthumbs">
                        <ul class="nopadding nomargin listnone listing-view">
                            <?php
                            foreach ($weekContent as $content){ ?>
                            <li class = "less-listing course-thumbs">
                            <div class = "bg-arrow">
                            <a href = "/article/<?php  echo($content->TE_day);?>">
                            <div class = "less-title">
                            <?php echo($content->TE_title_en); ?>
                            </div>
                            </a>
                            </div>
                            </li>
                            <?php } ?>



                            </ul>
                            </div>
                            </div>
                            <div class = "col-xs-12 col-sm-12">
                            <p class = "center nomargin"> <button type = "submit" class = "btn btn-default long-btn"><span class = "glyphicon glyphicon-search"></span> Show more</button></p>
                            </div>


                            </div>

                            </div>
                            </div>
                            </div>