
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12">
            <h1>Browse Courses by Week</h1>
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li><a href="/articles">Articles</a></li>
                <li class="active">Weeks</li>
            </ol>
        </div>
    </div>
</div> <!-- /container -->

<div class="container">
    <div class="body-bg">
        <div class="row">
            <div class="col-xs-12 col-sm-12">

                Sort by <a href="/articles/weeks">Weeks </a>| <a href="/articles/categories">Category</a>
            </div>

        </div>
        <div class="lessons-wrap">
            <div class="class-thumbs-wrap">
                <div class="row">
                    <div class="col-xs-4 col-sm-4">
                        <div class="coursebyweek">
                            <ul class="nopadding nomargin listnone">
                                <?php for ($i = 1; $i < 19; $i++) { ?>
                                    <li><a href="/articles/week/<?php echo $i;?>">Week <?php echo $i; ?></a></li>
                                <?php } ?>

                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-4 col-sm-4">
                        <div class="coursthumbs">
                            <ul class="nopadding nomargin listnone">
                                <?php for ($i = 19; $i < 37; $i++) { ?>
                                    <li><a href="/articles/week/<?php echo $i;?>">Week <?php echo $i; ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-4 col-sm-4">
                        <div class="coursthumbs">
                            <ul class="nopadding nomargin listnone">
                                <?php for ($i = 37; $i <= 52; $i++) { ?>
                                    <li><a href="/articles/week/<?php echo $i;?>">Week <?php echo $i; ?></a></li>
                                <?php } ?>

                            </ul>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </div>
</div>
</div> <!-- /wrap -->
