<div class="slider-wrap">
	<div class="container">
        <div class="row intro-text">
            <div class="col-md-7">
                <div class="content-wrap">
                    <div class="pitch-line">
                    	<h1>Welcome to ACILD SMS platform!</h1>
						<p>We are glad you are here. ACILD SMS platform enables <a href="http://www.acild.org" target="_blank">ACILD</a> and other agricultural players to communicate and share information with the farmers cost effectively and efficiently. Join your colleagues and see what ACILD can offer.</p>
                            <a class="btn btn-lg btn-primary"  href="/account/login">LOGIN</a> <a class="btn btn-lg btn-primary"  href="">CONTACT US</a> 
                        
                    </div>
                </div>
                <br/><br/><br/><br/>
            </div>
        </div>
	</div>
</div>