<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Compose Message</h2>
        <ol class="breadcrumb">
          <li><a href="/hub">Dashboard</a></li>
          <li><a href="/sms">SMS</a></li>
          <li class="active">Compose SMS</li>
        </ol>
      </div> <!-- /.content-header -->

      

      <div class="row">

        <div class="col-md-6 col-sm-9">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-hand-o-up"></i>
               Compose an SMS
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">

              <form role="form" method="POST" action="/sms/compose-sms">
                  <div class="form-group">
                    <label for="exampleInputEmail1">SMS</label>
                    <textarea class="form-control" name="message" placeholder="Type your SMS" rows="3"></textarea>
                  </div>
                  <div>                
                  <button type="submit" class="btn btn-success">Submit to Select Recipients</button>
                  <!-- <button type="submit" class="btn btn-default">DRAFT</button> -->
                  </div>
                </form>
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        </div><!-- /.col -->



        


      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->