<?php 
	
?>
<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">SMS Inbox</h2>
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li><a href="/inbox">SMS</a></li>
          <li class="active">Inbox</li>
        </ol>
      </div> <!-- /.content-header -->

      <div class="row">

        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-suitcase"></i>
                Messages
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true">
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true">Farmer</th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">MESSAGE</th>
                      <th data-filterable="true" class="hidden-xs hidden-sm">DATE</th>
                      <th data-filterable="false" class="text-center hidden-xs hidden-sm">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                   <?php 
                   if($this->responses){
                   		
                   	$responses = $this->responses;
                   	
                   	foreach ($responses as $response) {
						   
                   
                   ?>
                    
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td><?php  if($response->farmer_id){ echo $this->getFarmerName($response->farmer_id); } ?></td>
                      <td><?php if($response->message){ echo $response->message; }else{ echo '<i>Blank Message</i>'; }?></td>
                      <td><?php if($response->dateresponded){ echo $response->dateresponded; }?></td>
                      <td class="text-center">
                      <?php if($response->replied==0){  ?> 
                      <a href="/sms/reply/guid/<?php if($response->farmer_id){ echo $response->farmer_id; } ?>/id/<?php if($response->id){ echo $response->id; } ?>" class="btn btn-xs btn-success" > <i class="fa fa-reply"></i> reply  </a>
                      <?php }else{ ?>
                      	<i class="fa fa-check"></i> Replied
                      	<?php } ?> 
                      &nbsp;
                      &nbsp;
                      </td>
                    </tr>
                    
                    <?php 
							} 
						} ?>
                    
                  </tbody>
                </table>
               
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        

        </div> <!-- /.col -->

      </div> <!-- /.row -->
      
    </div> <!-- /.content-container -->
    
    
      
  </div> <!-- /.content -->

</div> <!-- /.container -->