<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">SMS Recipients</h2>
        <ol class="breadcrumb">
          <li><a href="/hub">Home</a></li>
          <li><a href="/sms/inbox">SMS</a></li>
          <li><a href="/sms/sent">Sent</a></li>
          <li class="active">View Recipients</li>
        </ol>
      </div> <!-- /.content-header -->

      <div class="row">

        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-users"></i>
                View Recipients
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true">
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true">Name</th>
                      <th data-filterable="true" data-sortable="true">Phone No</th>
                      <th>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                   <?php 
                   if($this->message){
                   	
                   foreach ($this->farmers as $key=>$value) {
                       
                   ?>
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td><?php if($value){ echo $this->getFarmerNameByPhone($value); }?></td>
                      <td><?php if($value){ echo ucwords($value); }?></td>
                      <td><a href="/sms/reply/guid/<?php if($sentsm->status){ echo $sentsm->status; } ?>" class="btn btn-xs btn-success" > <i class="fa fa-tick"></i> Sent  </a></td>
                    </tr>
                    <?php } 
                    }
                    ?>
                  </tbody>
               </table>
               <a href="#" class="btn btn-success" data-toggle="modal" data-target="#sendSMS">Send SMS</a>
               
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        

        </div> <!-- /.col -->

      </div> <!-- /.row -->
      
    </div> <!-- /.content-container -->
    

      
  </div> <!-- /.content -->

</div> 