<hr class="account-header-divider">

<div class="account-wrapper">

  <!-- <div class="account-logo">
    <img src="./img/logo-login.png" alt="Target Admin">
  </div> -->
  <br/><br/>

    <div class="account-body">

      <h3 class="account-body-title">Welcome back to ACILD.</h3>

      <h5 class="account-body-subtitle">Please sign in to get access.</h5>
      <?php 
        if($this->message){?>
         <div class="formheader">
            <div class="alert alert-danger">
                <p><?php echo $this->message;?></p>
            </div>
        </div>
        <?php    
           }
        ?>

      <form class="form account-form" method="POST" action="/account/login">

        <div class="form-group">
          <label for="login-username" class="placeholder-hidden">Email</label>
          <input type="text" class="form-control" name="email" id="login-username" placeholder="Email" tabindex="1">

        </div> <!-- /.form-group -->

        <div class="form-group">
          <label for="login-password" class="placeholder-hidden">Password</label>
          <input type="password" class="form-control" name="password" id="login-password" placeholder="Password" tabindex="2">
        </div> <!-- /.form-group -->

        <div class="form-group clearfix">
          <div class="pull-left">         
            <label class="checkbox-inline">
            <input type="checkbox" class="" value="" tabindex="3">Remember me
            </label>
          </div>

          <div class="pull-right">
            <a href="/account/forgot">Forgot Password?</a>
          </div>
        </div> <!-- /.form-group -->

        <div class="form-group">
          <button class="btn holo-info btn-block btn-lg"  >
            Signin &nbsp; <i class="fa fa-play-circle"></i>
          </button>
        </div> <!-- /.form-group -->

      </form>


    </div> <!-- /.account-body -->

   
  </div> <!-- /.account-wrapper -->