<hr class="account-header-divider">

<div class="account-wrapper">

  <!-- <div class="account-logo">
    <img src="./img/logo-login.png" alt="Target Admin">
  </div> -->
  <br/><br/>

    <div class="account-body">

      <h3 class="account-body-title">Password Reset.</h3>

      <h5 class="account-body-subtitle">Reset your password below...</h5>
      <?php 
        if($this->message){?>
         <div class="formheader">
            <div class="alert alert-danger">
                <p><?php echo $this->message;?></p>
            </div>
        </div>
        <?php    
           }
        ?>

      <form class="form account-form" method="POST" action="/account/password-reset/<?php if($this->ident && $this->token){ echo $this->ident.'/'.$this->token; }?>">

       <div class="form-group">
          <label for="login-password" class="placeholder-hidden">Password</label>
          <input type="password" class="form-control" name="password" id="login-password" placeholder="Password" tabindex="2">
        </div> <!-- /.form-group -->

        <div class="form-group">
          <label for="login-password" class="placeholder-hidden">Confirm Password</label>
          <input type="password" class="form-control" name="cpassword" id="login-password" placeholder="Password" tabindex="2">
        </div> <!-- /.form-group -->
        
        <div class="form-group">
          <button class="btn holo-info btn-block btn-lg"  >
            Reset &nbsp; <i class="fa fa-play-circle"></i>
          </button>
        </div> <!-- /.form-group -->

      </form>


    </div> <!-- /.account-body -->

   
  </div> <!-- /.account-wrapper -->