<?php 
	$contents = $this->contents;
?>
<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Content</h2>
        <ol class="breadcrumb">
          <li><a href="/">Home</a></li>
          <li class="active"><a href="">Content</a></li>
        </ol>
       
            
      </div> <!-- /.content-header -->
	
      	
      
      <div class="row">

        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-table"></i>
                Content Saved
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true">
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Content</th>
                      <th data-filterable="true" class="hidden-xs hidden-sm">Created By</th>
                      <th data-filterable="true" data-sortable="true">Date Created</th>
                      
                      <th data-filterable="false" class="text-center hidden-xs hidden-sm">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php 
                    	foreach ($contents as $content) {
                    ?>
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td>
                      	<a href="/content/view/guid/<?php if($content->guid){ echo $content->guid; } ?> ">
                      	<?php 
                      		if($content->title){ echo $content->title; }
							
                      	?> 
                      	</a>
                      	<?php 
                      		if($content->attachment){ echo ' <i class="fa fa-paperclip"></i>'; }
						?>
                      	</td>
                      
                      <td class="hidden-xs hidden-sm">
                      	<?php 
                      		if($content->organization){ echo $this->getUserOrg($content->organization); }
                      	?> 
                      </td>
                      <td>
                      	<?php 
                      		if($content->dateentered){ echo $content->dateentered; }
                      	?> 
                      </td>
                      <td class="text-center">
                      &nbsp;
                      <a href="/content/view/guid/<?php if($content->guid){ echo $content->guid; } ?> " class="btn btn-xs btn-success"><i class="fa fa-eye"></i> view</a>
                      </td>
                    </tr>
                    
                    <?php } ?>
                    
                  </tbody>
                </table>
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        </div> <!-- /.col -->

      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->