<div class="container">

  <div class="content">

    <div class="content-container">    

      <div class="content-header">
        <h2 class="content-header-title">Create Survey</h2>
        <ol class="breadcrumb">
          <li><a href="index.php">Home</a></li>
          <li class="active">Create Survey</li>
        </ol>
      </div> <!-- /.content-header -->

      <div class="row">
         <div class="col-md-12">
         	<div>
                <form class="form-horizontal" role="form" action="/survey-create-questions.php">
                  <div class="form-group">
                    <label for="surveyTitle" class="col-sm-2 control-label">SURVEY TITLE</label>
                    <div class="col-md-6 col-sm-6">
                      <input type="text" class="form-control" id="surveyTitle" placeholder="e.g Social Audit Questionnaire">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-success">Create</button>
                    </div>
                  </div>
              </form>
            </div>
         </div>
       </div><!--/.row-->
        <br/>
         <br/>
       <div class="row">
         <div class="col-md-12">
         <h4 class="content-header-title">Sample Titles</h4>
       	   <h5>Farmers Income</h5>
           <h5>Amount of Produce per year</h5>
           <h5>Social Audit Questionnaire</h5>
         </div>
       </div><!-- /.row-->

    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> 