<?php 
	$agrovets = $this->agrovets;
?>
<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Agrovets</h2>
        <ol class="breadcrumb">
          <li><a href="index.php">Home</a></li>
          <li class="active"><a href="">Agrovets</a></li>
        </ol>
      </div> <!-- /.content-header -->

      <div class="row">
	
		<?php if($this->mid || $this->message ){?>
		<div class="col-md-12">
				<div class="alert <?php if($this->mid==1){ echo "alert-danger";}else{ echo "alert-success"; }?> alert-dismissable">
				  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
				  <?php echo ucfirst($this->message);?>
				</div>
		</div>
		<?php } ?>
		
        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-table"></i>
                Registered Agrovets
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true"
              >
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Agrovet</th>
                      <th data-filterable="true" data-sortable="true">Contact Phone</th>
                      <th data-filterable="true" class="hidden-xs hidden-sm">EMAIL</th>
                      <th data-filterable="true" class="hidden-xs hidden-sm">DATE REGISTERED</th>
                      <th data-filterable="false" class="text-center hidden-xs hidden-sm">ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                    <?php 
                    	foreach ($agrovets as $agrovet) {
							
                    ?>
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td>
                      	
                      	<a href="/agrovets/view/agrovet/<?php  if($agrovet->guid){ echo $agrovet->guid; }?>">
                      		<?php 
	                      		if($agrovet->names){ echo $agrovet->names; }
	                      	?> 
                      		</a>
                      	
                      	</td>
                      <td>
                      	<?php 
                      		if($agrovet->phoneno){ echo $agrovet->phoneno; }
                      	?> 
                      </td>
                      <td>
                      	<?php 
                      		if($agrovet->email){ echo $agrovet->email; }
                      	?> 
                      </td>
                      <td class="hidden-xs hidden-sm">
                      	<?php 
                      		if($agrovet->dateregistered){ echo $agrovet->dateregistered; }
                      	?> 
                      </td>
                      <td class="text-center">
                      &nbsp;
                      <a class="btn btn-xs btn-success" href="/agrovets/view/agrovet/<?php  if($agrovet->guid){ echo $agrovet->guid; }?>"><i class="fa fa-eye"></i> View</a>
                      </td>
                    </tr>
                    
                    <?php } ?>
                    
                  </tbody>
                </table>
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        

        </div> <!-- /.col -->

      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->