<?php 
 if($this->farmers){
 	$farmers = $this->farmers;
 }
?>
<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Farmers</h2>
        <ol class="breadcrumb">
          <li><a href="./index.html">Home</a></li>
          <li class="active">Farmers</li>
        </ol>
      </div> <!-- /.content-header -->

      <div class="row">

        <div class="col-md-12">

          <div class="portlet">

            <div class="portlet-header">

              <h3>
                <i class="fa fa-users"></i>
                Farmers
              </h3>

            </div> <!-- /.portlet-header -->

            <div class="portlet-content">           

              <div class="table-responsive">

              <table 
                class="table table-striped table-bordered table-hover table-highlight table-checkable" 
                data-provide="datatable" 
                data-display-rows="10"
                data-info="true"
                data-search="true"
                data-length-change="true"
                data-paginate="true">
                  <thead>
                    <tr>
                      <th class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Name</th>
                      <th data-direction="asc" data-filterable="true" data-sortable="true">Phone Number</th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Gender</th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">County</th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Ward</th>
                      <th data-filterable="true" data-sortable="true" data-direction="desc">Date Registered</th>
                    </tr>
                  </thead>
                  <tbody>
                   <?php 
                   foreach ($farmers as $farmer) {
                       
                   ?>
                    <tr>
                      <td class="checkbox-column">
                        <input type="checkbox" class="icheck-input">
                      </td>
                      <td><?php if($farmer->names){ echo ucwords($farmer->names); }?></td>
                      <td><?php if($farmer->phoneno){ echo $farmer->phoneno; }?></td>
                      <td><?php if($farmer->gender){ echo ucfirst($farmer->gender); }?></td>
                      <td><?php if($farmer->county){ echo $farmer->county; }?></td>
                      <td><?php if($farmer->ward){ echo $farmer->ward; }?></td>
                      <td><?php if($farmer->dateregistered){ echo $farmer->dateregistered; }?></td>
                    </tr>
                    <?php } ?>
                  </tbody>
               </table>
               <a href="#" class="btn btn-success" data-toggle="modal" data-target="#sendSMS">Send SMS</a>
               
              </div> <!-- /.table-responsive -->
              

            </div> <!-- /.portlet-content -->

          </div> <!-- /.portlet -->

        

        </div> <!-- /.col -->

      </div> <!-- /.row -->
      
    </div> <!-- /.content-container -->
    <div class="modal fade" id="sendSMS" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
			    <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			        <h4 class="modal-title" id="myModalLabel">SMS Message</h4>
			    </div>
			    <div class="modal-body">
			        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
			    </div>
			 	<div class="modal-footer">
			        <a class="btn btn-success" data-dismiss="modal">CANCEL</a>
			        <a href="/create-sms.php" class="btn btn-warning">SEND SMS</a>
			     </div>
			 </div>
		</div>
	</div>

      
  </div> <!-- /.content -->

</div> 