
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <title>ACILD:: Homepage</title>

  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <link rel="shortcut icon" href="/favicon.ico" />

  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,400,600,700">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oswald:400,300,700">
  <link rel="stylesheet" href="/css/font-awesome.min.css">
  <link rel="stylesheet" href="/js/libs/css/ui-lightness/jquery-ui-1.9.2.custom.min.css">
  <link rel="stylesheet" href="/css/bootstrap.min.css">

  <!-- Plugin CSS -->
  <link rel="stylesheet" href="/js/plugins/morris/morris.css">
  <link rel="stylesheet" href="/js/plugins/icheck/skins/minimal/blue.css">
  <link rel="stylesheet" href="/js/plugins/select2/select2.css">
  <link rel="stylesheet" href="/js/plugins/fullcalendar/fullcalendar.css">

  <!-- App CSS -->
  <link rel="stylesheet" href="/css/target-admin.css">
  <link rel="stylesheet" href="/css/custom.css">
  <link rel="stylesheet" href="/css/felix.css">
  


  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
</head>

<body>

  <div class="navbar">

  <div class="container">

    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <i class="fa fa-bars"></i>
      </button>

      <a class="navbar-brand navbar-brand-image" href="/">
         <div class="col-md-2">
           <div class="logo">
        	<img src="/img/acild_logo_2.png"/> 
		   </div>
         </div>
      </a>

    </div> <!-- /.navbar-header -->

    <div class="navbar-collapse collapse">
    
    	<ul class="nav navbar-nav navbar-right">   
		 
        <li>
          <a href="#" class=" bttn btn-outline">Contact Us</a>
        </li>   
          
        <li>
          <a href="/account/login" class="bttn btn-outline">Login</a>
        </li>    

        

      </ul>

    </div> <!--/.navbar-collapse -->

  </div> <!-- /.container -->

</div> <!-- /.navbar -->


<?php echo $this->layout()->content; ?>



<footer class="footer">

  <div class="container">

    <div class="row">

      <div class="col-sm-6 col-md-12">

       <!-- <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>  -->

        <hr>    

        <p>&copy; 2014 ACILD. All rights reserved <span class="pull-right"> Product of <a href="http://www.acild.org">ACILD</a></span> </p>

      </div>


    </div>

  </div>
  
</footer>

  <script src="./js/libs/jquery-1.10.1.min.js"></script>
  <script src="./js/libs/jquery-ui-1.9.2.custom.min.js"></script>
  <script src="./js/libs/bootstrap.min.js"></script>

  <!--[if lt IE 9]>
  <script src="./js/libs/excanvas.compiled.js"></script>
  <![endif]-->
  
  <!-- Plugin JS -->
  <script src="./js/plugins/icheck/jquery.icheck.js"></script>
  <script src="./js/plugins/select2/select2.js"></script>
  <script src="./js/libs/raphael-2.1.2.min.js"></script>
  <script src="./js/plugins/morris/morris.min.js"></script>
  <script src="./js/plugins/sparkline/jquery.sparkline.min.js"></script>
  <script src="./js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
  <script src="./js/plugins/fullcalendar/fullcalendar.min.js"></script>

  <!-- App JS -->
  <script src="./js/target-admin.js"></script>
  
  <!-- Plugin JS -->
  <script src="./js/demos/dashboard.js"></script>
  <script src="./js/demos/calendar.js"></script>
  <script src="./js/demos/charts/morris/area.js"></script>
  <script src="./js/demos/charts/morris/donut.js"></script>

  


  
</body>
</html>



