<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="/ico/favicon.ico">

        <title>CiPELT :: Home</title>

        <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/custom.cip.css" rel="stylesheet">

        <!-- Custom styles for this template -->


        <!-- Just for debugging purposes. Don't actually copy this line! -->
        <!--[if lt IE 9]><script src="/js/ie8-responsive-file-warning.js"></script><![endif]-->

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <!-- Static navbar -->
        <div id="wrap">
            <div class="navbar navbar-default navbar-static-top main-nav" role="navigation">
                <div class="container">
                    <div class="top-menu-bar-wrap">
                        <div class="col-xs-6 col-sm-6">
                            <div class="nav-courses-wrap">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">WEEKS <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="/articles/week/1">Week 1</a></li>
                                    <li><a href="/articles/week/2">Week 2</a></li>
                                    <li><a href="/articles/week/3">Week 3</a></li>
                                    <li><a href="/articles/week/4">Week 4</a></li>
                                    <li><a href="/articles/week/5">Week 5</a></li>
                                    <li><a href="/articles/week/6">Week 6</a></li>
                                    <li class="divider"></li>
                                    <li><a href="/articles/weeks"><span class="glyphicon glyphicon-list"></span> &nbsp;All Weeks &rarr;</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-6 pull-right">
                            <div class="pull-right home-icons">
                                <a href="/articles/categories"><img class="home-icons-bal" src="/images/browse.png" alt="browse"/> Browse</a> &nbsp;&nbsp; <a href="/search"><img class="home-icons-bal" src="/images/searchicon.png" alt="Search" /> Search</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="navbar navbar-default navbar-static-top second" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="pull-left menu-text">Menu</span>
                            <span class="pull-left menu-icon">
                                <span class="sr-only"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </span>
                            <div class="clearfix"></div>

                        </button>
                        <a class="navbar-brand" href="/"><img class="logoimg" src="/images/logo_full.png" /></a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="">Home</a></li>
                            <li><a href="/articles/categories">Categories</a></li>
                            <li><a href="/articles/weeks">Weeks</a></li>

                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="/about">About CiPELT</a></li>
                            <li><a href="/support">Support</a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>

            <?php echo $this->layout()->content; ?>

            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="copyright-wrap">
                                <p class="nomargin center">Brought to you by <a href=""> <img class="bal-copy" src="/images/bclogo.png" /></a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <!-- Bootstrap core JavaScript
            ================================================== -->
            <!-- Placed at the end of the document so the pages load faster -->
            <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
            <script src="/js/bootstrap.min.js"></script>
    </body>
</html>
