<div class="container">

  <div class="content">

    <div class="content-container">

      

      <div class="content-header">
        <h2 class="content-header-title">Gallery</h2>
        <ol class="breadcrumb">
          <li><a href="index.php">Home</a></li>
          <li class="active">Gallery</li>
        </ol>
      </div> <!-- /.content-header -->
      
      <h4 class="heading">Photo Gallery</h4>
      
      <div class="row">

        <div class="col-md-3 col-sm-6">

          <div class="thumbnail">
            <div class="thumbnail-view">
              <a href="./img/photos/blur-lg.jpg" class="thumbnail-view-hover ui-lightbox"></a>
              <img src="./img/photos/blur-sm.jpg" style="width: 100%" alt="Gallery Image" />
            </div>

            <div class="caption">
              <h3>KARI</h3>
              <p>KARI Outreach at kiambu.</p>
            </div>
          </div>  <!-- /.thumbnail -->         

        </div> <!-- /.col -->


        <div class="col-md-3 col-sm-6">

          <div class="thumbnail">
            <div class="thumbnail-view">
              <a href="./img/photos/clock-lg.jpg" class="thumbnail-view-hover ui-lightbox"></a>
              <img src="./img/photos/clock-sm.jpg" style="width: 100%" alt="Gallery Image" />
            </div>

            <div class="caption">
              <h3>Machakos Agrovets</h3>
              <p>Rewarding farmers after selling.</p>
            </div>
          </div> <!-- /.thumbnail -->      

        </div> <!-- /.col -->



        <div class="col-md-3 col-sm-6">

          <div class="thumbnail">
            <div class="thumbnail-view">
              <a href="./img/photos/lens-lg.jpg" class="thumbnail-view-hover ui-lightbox"></a>
              <img src="./img/photos/lens-sm.jpg" style="width: 100%" alt="Gallery Image" />
            </div>

            <div class="caption">
              <h3>Nyeri Farmers</h3>
              <p>Farmers at responding to survey questions</p>
              
            </div>
          </div> <!-- /.thumbnail -->     

        </div> <!-- /.col -->



        <div class="col-md-3 col-sm-6">

          <div class="thumbnail">
            <div class="thumbnail-view">
              <a href="./img/photos/rust-lg.jpg" class="thumbnail-view-hover ui-lightbox"></a>
              <img src="./img/photos/rust-sm.jpg" style="width: 100%" alt="Gallery Image" />
            </div>

            <div class="caption">
              <h3>ACILD</h3>
              <p>Educating farmers about ACILD platform</p>
              
            </div>
          </div> <!-- /.thumbnail -->         

        </div> <!-- /.col -->

      </div> <!-- /.row -->


    </div> <!-- /.content-container -->
      
  </div> <!-- /.content -->

</div> <!-- /.container -->